language: python
python:
  - "3.9"
services:
  - postgresql
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

script:
  - pylint library
  - coverage run -m unittest discover library/tests
  - coverage report

after_success:
  - coveralls