language: python
python:
  - "3.9"
services:
  - postgresql
install:
  - pip install -r requirements.txt

before_script:
  -  psql -c 'create database Test;' -U postgres
  - export PYTHONPATH=/home/travis/build/lubart2517/Epam_project/library/

script:
  - pylint library
  - coverage run -m unittest discover library/tests
  - coverage report

after_success:
  - coveralls